blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/d99kris/nchat/discussions/new?category=ideas
    about: Suggest a new feature by starting a new discussion.
  - name: Question
    url: https://github.com/d99kris/nchat/discussions/new?category=q-a
    about: Ask a question by starting a new discussion.
